spring:
  data:
    mongodb:
      username: admin
      password: password
      authentication-database: admin
      host: mongodb
      port: 27017
      database: mcpdb
  application:
    name: user-service
  webflux:
    base-path: api

